### ISSUE TITLE
Generating and solving conflicts

### ISSUE THREAD

**Issue by bilanuser** [UCL-COMP0233-22-23/RSE-Classwork#16]
![image](https://user-images.githubusercontent.com/115076400/198019598-3a99cda2-4de5-4cca-b646-8f551bd41ca2.png)
![65b90b5edf9e15c84cb2110b5a45005](https://user-images.githubusercontent.com/115076400/198020033-f5db7bef-b968-4ec7-96e9-30037dd6a8e3.jpg)
Answers [UCL-COMP0233-22-23/RSE-Classwork#3](https://github.com/UCL-COMP0233-22-23/RSE-Classwork/issues/3)

**Comment by dpshelio** [comment]
You had to do this in an issue in your fork (see point 5 of #3)
