### ISSUE TITLE
Generating and resolving conflicts

### ISSUE THREAD

**Issue by greneus** [UCL-COMP0233-22-23/RSE-Classwork#6]
At merge conflict, README.me looks like (in VIM):

```
<<<<<<< HEAD
Hola
=======
Hello World
>>>>>>> new-branch
```
By deleting the lines except for Hello world, the merge conflict is resolved and the result can be committed.

**Comment by dpshelio** [comment]
You had to create this issue in your fork (see point 5 in #3)
